// 获取商品类型列表
export const FETCH_CATEGORY          = 'FETCH_CATEGORY'
export const FETCH_CATEGORY_SUCCESS  = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_ERROR    = 'FETCH_CATEGORY_ERROR'

// 获取单个商品类型下的库存列表
export const FETCH_INVENTORY         = 'FETCH_INVENTORY'
export const FETCH_INVENTORY_SUCCESS = 'FETCH_INVENTORY_SUCCESS'
export const FETCH_INVENTORY_ERROR   = 'FETCH_INVENTORY_ERROR'

// 获取入库的库存列表
export const FETCH_IN_STOCK         = 'FETCH_IN_STOCK'
export const FETCH_IN_STOCK_SUCCESS = 'FETCH_IN_STOCK_SUCCESS'
export const FETCH_IN_STOCK_ERROR   = 'FETCH_IN_STOCK_ERROR'

// 获取入库的库存列表
export const FETCH_OUT_STOCK         = 'FETCH_OUT_STOCK'
export const FETCH_OUT_STOCK_SUCCESS = 'FETCH_OUT_STOCK_SUCCESS'
export const FETCH_OUT_STOCK_ERROR   = 'FETCH_OUT_STOCK_ERROR'

// 获取营业报表-收入统计
export const FETCH_INCOME           = 'FETCH_INCOME'
export const FETCH_INCOME_SUCCESS   = 'FETCH_INCOME_SUCCESS'
export const FETCH_INCOME_ERROR     = 'FETCH_INCOME_ERROR'

// 获取营业报表-收入统计详情
export const FETCH_INCOME_DETAIL         = 'FETCH_INCOME_DETAIL'
export const FETCH_INCOME_DETAIL_SUCCESS = 'FETCH_INCOME_DETAIL_SUCCESS'
export const FETCH_INCOME_DETAIL_ERROR   = 'FETCH_INCOME_DETAIL_ERROR'

// 收入统计详情下 根据获取订单商品明细
export const FETCH_ORDER         = 'FETCH_ORDER'
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDER_ERROR   = 'FETCH_ORDER_ERROR'

// 获取营业概况 数据
export const FETCH_SUMMARY         = 'FETCH_SUMMARY'
export const FETCH_SUMMARY_SUCCESS = 'FETCH_SUMMARY_SUCCESS'
export const FETCH_SUMMARY_ERROR   = 'FETCH_SUMMARY_ERROR'

// 获取营业报表-交班记录列表
export const FETCH_WORK_RECORD         = 'FETCH_WORK_RECORD'
export const FETCH_WORK_RECORD_SUCCESS = 'FETCH_WORK_RECORD_SUCCESS'
export const FETCH_WORK_RECORD_ERROR   = 'FETCH_WORK_RECORD_ERROR'

// 获取营业报表-钱箱统计列表
export const FETCH_CASH_COUNT         = 'FETCH_CASH_COUNT'
export const FETCH_CASH_COUNT_SUCCESS = 'FETCH_CASH_COUNT_SUCCESS'
export const FETCH_CASH_COUNT_ERROR   = 'FETCH_CASH_COUNT_ERROR'

// 获取营业报表-商品统计列表
export const FETCH_GOODS_COUNT         = 'FETCH_GOODS_COUNT'
export const FETCH_GOODS_COUNT_SUCCESS = 'FETCH_GOODS_COUNT_SUCCESS'
export const FETCH_GOODS_COUNT_ERROR   = 'FETCH_GOODS_COUNT_ERROR'

// 获取客户资料管理 列表
export const FETCH_PROFILE_LIST         = 'FETCH_PROFILE_LIST'
export const FETCH_PROFILE_LIST_SUCCESS = 'FETCH_PROFILE_LIST_SUCCESS'
export const FETCH_PROFILE_LIST_ERROR   = 'FETCH_PROFILE_LIST_ERROR'

// 获取客户管理资料管理 详情
export const FETCH_PROFILE_DETAIL         = 'FETCH_PROFILE_DETAIL'
export const FETCH_PROFILE_DETAIL_SUCCESS = 'FETCH_PROFILE_DETAIL_SUCCESS'
export const FETCH_PROFILE_DETAIL_ERROR   = 'FETCH_PROFILE_DETAIL_ERROR'

// 获取单个用户资料&消费总额
export const FETCH_SINGLE_DETAIL         = 'FETCH_SINGLE_DETAIL'
export const FETCH_SINGLE_DETAIL_SUCCESS = 'FETCH_SINGLE_DETAIL_SUCCESS'
export const FETCH_SINGLE_DETAIL_ERROR   = 'FETCH_SINGLE_DETAIL_ERROR'

// 获取提醒历史记录列表
export const FETCH_REMIND_RECORD         = 'FETCH_REMIND_RECORD'
export const FETCH_REMIND_RECORD_SUCCESS = 'FETCH_REMIND_RECORD_SUCCESS'
export const FETCH_REMIND_RECORD_ERROR   = 'FETCH_REMIND_RECORD_ERROR'

// 获取 客户详情编辑资料
export const FETCH_CLIENT_DETAIL         = 'FETCH_CLIENT_DETAIL'
export const FETCH_CLIENT_DETAIL_SUCCESS = 'FETCH_CLIENT_DETAIL_SUCCESS'
export const FETCH_CLIENT_DETAIL_ERROR   = 'FETCH_CLIENT_DETAIL_ERROR'

// 提交 客户资料修改
export const SUBMIT_CLIENT_DETAIL         = 'SUBMIT_CLIENT_DETAIL'
export const SUBMIT_CLIENT_DETAIL_SUCCESS = 'SUBMIT_CLIENT_DETAIL_SUCCESS'
export const SUBMIT_CLIENT_DETAIL_ERROR   = 'SUBMIT_CLIENT_DETAIL_ERROR'
